f = open('o_en.txt', 'r', encoding='utf-8')
g = open('o_zh.txt', 'r', encoding='utf-8')
t=open('o_result.txt', 'r', encoding='utf-8')
w=open('2000012952-岳禹彤-enzh1.txt', 'w', encoding='utf-8')

line1 = f.readline()
line2 = g.readline()
line3 = t.readline()
while(line1):
    w.write(line1[0:len(line1)-1])
    w.write('\t')
    w.write(line2[0:len(line2)-1])
    w.write('\t')
    w.write(line3)
    line1 = f.readline()
    line2 = g.readline()
    line3 = t.readline()
f.close()
g.close()
t.close()
w.close()